<a href="https://colab.research.google.com/github/Akshat-2503-AI/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as ap

In [ ]:
a = ap.array([1,3,9,0,'2'])
print(a)

['1' '3' '9' '0' '2']


In [ ]:
ap_arr = ap.array([3,3,3,3,3.3,'hello',False])
print(bool(ap_arr[-1])) # it will change all elements into string.

a = False
print(bool(a))

True
False


In [ ]:
a = 'akshat'
print(bool(a))

True


In [ ]:
a = '0'
print(bool(a))


True


In [ ]:
a = 0
print(bool(a))
#only zero in integer gives false.

False


In [ ]:
a = ap.zeros((3,2))
print(a)

# to print matrix(row,column)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
a = ap.zeros((2,3,4),dtype=int)
print(a)
print(type(a[0][0][0]))
# (no of matrix,elements in column,elements in row)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a = ap.full(4,6,dtype=int)
print(a)
#empty = to print random numbers
#full = to print a particular number

[6 6 6 6]


In [ ]:
a = ap.arange(4,10,2)
print(a)
#(starting no,last no,gap between)

a = ap.linspace(4,10,2)
print(a)


[4 6 8]
[ 4. 10.]


In [ ]:
a = ap.linspace(2,14,4,dtype=int)
print(a)
#(starting value,end value,gap)

[ 2  6 10 14]


In [ ]:
a = ap.ones((2,3,4))
print(ap.shape(a))
print(ap.size(a))


(2, 3, 4)
24


In [ ]:
from numpy import random


In [ ]:
a = ap.random.randint(50)
print(a)

20


In [ ]:
import numpy as ap

In [ ]:
a = ap.random.choice([2,4,2,9],5)
print(a)
# it tells no of values to print from selected values

[2 9 9 2 4]


In [ ]:
a = ap.array([2,4,6,8])
b = ap.array([2,5,6,8,4])
print(a,b)
print(a*2)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[2 4 6 8 7] [2 5 6 8 4]
[ 4  8 12 16 14]
[ 4  9 12 16 11]
[ 0 -1  0  0  3]
[1.   0.8  1.   1.   1.75]
[ 4 20 36 64 28]


In [ ]:
a = [2,4,6,8]
b = [2,5,7,4]
print(a,b)
print(a+b)


[2, 4, 6, 8] [2, 5, 7, 4]
[2, 4, 6, 8, 2, 5, 7, 4]


In [ ]:
a = ap.random.randint(2,15,5)
print(a)
#(start,end,no of random elements to print in between start and end)

[ 8 13  3  5  7]


In [ ]:
a = ap.random.randint(2,15,5)
print(a)

b = a.reshape((2,3))
print(b)

[ 4  6  8  7 14]


ValueError: cannot reshape array of size 5 into shape (2,3)

In [ ]:
a = ap.random.randint(2,15,9)
print(a)
b = a.reshape((3,3)) #row and columns
print(b)
c = a.transpose()
print(c)

[11  3  7 12  3 14 12  5  3]
[[11  3  7]
 [12  3 14]
 [12  5  3]]
[11  3  7 12  3 14 12  5  3]


In [ ]:
a = ap.random.randint(2,15,9)
b = ap.random.randint(1,19,6)
print(ap.concatenate((a,b),)) #link both a and b
print(ap.sort(ap.concatenate((a,b))))

[ 3  1  8  5  7 14 13 10 13 11 12  8  4  8 13]
[ 1  3  4  5  7  8  8  8 10 11 12 13 13 13 14]


In [ ]:
a = ap.random.randint(1,15,6)
b = ap.random.randint(1,19,6)
print(a)
print(b)
c = ap.where(b>2,b,a) # condition if true print b otherwise print a.
print(c)

[ 5 13  6 12  4  9]
[11  3 17  1  8  4]
[11  3 17 12  8  4]


In [ ]:
scores  = input().split()
print(scores)

#days = ['mon','tue','wed','thu','fri','sat','sun']

scores = [int(x) for x in scores]
print(scores)


1 2 3 4 5 6 7
['1', '2', '3', '4', '5', '6', '7']
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
a = ap.array([3,3,3,3])
b = a
b[2] = 1

print(a,b)

[3 3 1 3] [3 3 1 3]


In [ ]:

user_input = input("Enter words separated by spaces: ").split()
a = ap.fromiter(user_input, dtype='U20')

c = input().split()
ab = [int(x) for x in c]

c = ap.max(ab)
print(c)
ind = ap.flatnonzero(ab == c)


print(a[ind],"=",c)

Enter words separated by spaces: yeah no ok
123 5 89
123
['yeah'] = 123


In [ ]:
a = ap.array(['soap','biscuit','namkeen'])
c = input().split()
ab = [int(x) for x in c]


c = ap.max(ab)
print(c)
ind = ap.flatnonzero(ab == c)


print(a[ind],"=",c)

30 40 50
50
['namkeen'] = 50


In [ ]:
# Create a 5*5 matrix of random integers (1-90)

mat = ap.random.randint(1,90,(5,5))
print(mat)


[[84 17 33 37 84]
 [57 61 52 84 44]
 [80  6 34 75 61]
 [38  2 10 28 62]
 [62 56 19 79 15]]


In [ ]:
# Find mean of vales row and column wise.
mat = ap.random.randint(1,90,(5,5))
print(mat)
print(ap.mean(mat,axis=0))
print(ap.mean(mat,axis=1))

[[88  7 31 11 58]
 [29 16 65 86 83]
 [63 22 44 42 48]
 [78 62 31 13 54]
 [10 35 82 21 63]]
[53.6 28.4 50.6 34.6 61.2]
[39.  55.8 43.8 47.6 42.2]


In [ ]:
# Replace all even numbers with -1
mat = ap.random.randint(1,90,(5,5))
mat1 = ap.where(mat%2==0,-1,mat)
print(mat1)

[[13 -1 23 -1 13]
 [-1 21 -1 51 -1]
 [31 13 51 89 -1]
 [71 -1 29 41 61]
 [15 -1 27 77  7]]


In [ ]:
# sort the array row and column wise.
mat = ap.random.randint(1,90,(5,5))
mat = ap.sort(mat,axis=0)
mat = ap.sort(mat,axis=1)
print(mat)

[[ 1  9 12 36 44]
 [ 7 30 43 51 75]
 [ 7 33 56 59 86]
 [10 60 71 76 87]
 [81 81 82 89 89]]


In [ ]:
# Find row and column wise sum separately.
mat = ap.random.randint(1,90,(5,5))
mat = ap.sum(mat,axis=0)
mat = ap.sum(mat,axis=0)
print(mat)

1055


In [ ]:
# count the number of -ve in each column
mat = ap.random.randint(-90,90,(5,5))
mat = ap.where(mat<0,1,0)
mat = ap.sum(mat,axis=0)
print(mat)

[3 1 3 3 3]


In [ ]:
# inventory control system
stock = ap.random.randint(1,20,(5,5))
demand = ap.random.randint(1,20,(5,5))
remaining_stock = stock - demand
print(remaining_stock)

modified = ap.where(remaining_stock<0,0,remaining_stock)
print(modified)

total_shortage = ap.sum(ap.where(remaining_stock<0,remaining_stock  -1,0))
print(total_shortage)

product_shortage = ap.sum(ap.where(remaining_stock<0,1,0))
print(total_shortage,product_shortage)

sorted = ap.sort(modified,axis = 1)



[[  5   4  10  -5  -7]
 [  3  11  -3   6   3]
 [ -2   2   1  12   1]
 [ -3  11 -11   0  -1]
 [ -6  16  -5  -1  -6]]
[[ 5  4 10  0  0]
 [ 3 11  0  6  3]
 [ 0  2  1 12  1]
 [ 0 11  0  0  0]
 [ 0 16  0  0  0]]


TypeError: 'numpy.int64' object is not callable